name: mice-data
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - blinker=1.7.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - certifi=2024.2.2
  - click=8.1.7
  - contourpy=1.2.0
  - cycler=0.12.1
  - flask=3.0.2
  - fonttools=4.48.1
  - freetype=2.12.1
  - importlib-metadata=7.0.1
  - itsdangerous=2.1.2
  - jinja2=3.1.3
  - kiwisolver=1.4.5
  - lcms2=2.16
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcxx=16.0.6
  - libdeflate=1.19
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libopenblas=0.3.26
  - libpng=1.6.42
  - libsqlite=3.45.1
  - libtiff=4.6.0
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libzlib=1.2.13
  - llvm-openmp=17.0.6
  - markupsafe=2.1.5
  - matplotlib=3.8.2
  - matplotlib-base=3.8.2
  - munkres=1.1.4
  - ncurses=6.4
  - numpy=1.26.4
  - openjpeg=2.5.0
  - openssl=3.2.1
  - packaging=23.2
  - pillow=10.2.0
  - pip=24.0
  - pthread-stubs=0.4
  - pyparsing=3.1.1
  - python=3.10.13
  - python-dateutil=2.8.2
  - python_abi=3.10
  - readline=8.2
  - setuptools=69.0.3
  - six=1.16.0
  - tk=8.6.13
  - tornado=6.3.3
  - tzdata=2024a
  - unicodedata2=15.1.0
  - werkzeug=3.0.1
  - wheel=0.42.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - zipp=3.17.0
  - zstd=1.5.5
  - pip:
      - confluent-kafka==2.3.0